name: Backend Deployment

on:
  push:
    branches: [main]
    paths:
      - "cc-backend/**"
      - ".github/workflows/backend-deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    name: Deploy Azure Infrastructure
    runs-on: ubuntu-latest
    environment: Azure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./cc-backend/azure-infrastructure/bicep/main.bicep
          parameters: baseName=ccompass environment=dev
          deploymentName: ccompass-infra-${{ github.run_number }}

  deploy-function-app:
    name: Deploy Function App
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    environment: Azure
    defaults:
      run:
        working-directory: ./cc-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./cc-backend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Storage Account Key
        id: get-storage-key
        run: |
          STORAGE_KEY=$(az storage account keys list --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --account-name ccompassdev --query '[0].value' -o tsv)
          CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=ccompassdev;AccountKey=${STORAGE_KEY};EndpointSuffix=core.windows.net"
          echo "CONNECTION_STRING=${CONNECTION_STRING}" >> $GITHUB_OUTPUT

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: "ccompass-func-dev"
          package: "./cc-backend"
          respect-funcignore: true
          scm-do-build-during-deployment: true
          enable-oryx-build: false
        env:
          AzureWebJobsStorage: ${{ steps.get-storage-key.outputs.CONNECTION_STRING }}
          WEBSITE_CONTENTAZUREFILECONNECTIONSTRING: ${{ steps.get-storage-key.outputs.CONNECTION_STRING }}
