name: Frontend Deployment

on:
  push:
    branches: [main]
    paths:
      - "cc-frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    environment: Azure
    defaults:
      run:
        working-directory: ./cc-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./cc-frontend/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    #   - name: Deploy to Azure Static Web Apps
    #     uses: Azure/static-web-apps-deploy@v1
    #     with:
    #       azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
    #       repo_token: ${{ secrets.GITHUB_TOKEN }}
    #       action: "upload"
    #       app_location: "./cc-frontend"
    #       api_location: ""
    #       output_location: "dist"
    #       skip_app_build: true
