name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "cc-frontend/**"
      - "cc-backend/**"
      - ".github/workflows/frontend-deploy.yml"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - "cc-frontend/**"
      - "cc-backend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    environment: Azure
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_API_BASE_URL: https://ccompass-func-dev.azurewebsites.net/api
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "cc-frontend"
          api_location: "cc-backend"
          output_location: "dist"
